### ISSUE TITLE
请问能生成mobi或epub版么

### ISSUE THREAD

**Issue by lekai63** [careywyr/UnderstandingDeepLearning-ZH-CN#1]
如题，主要是能方便在移动设备上看。（比如坐地铁时）

**Comment by careywyr** [comment]
其实也试过，但没找到合适的转换的方式，试了pandoc和tex4ebook还有在线的那种，要么报错要么效果不行。如果想要移动设备上阅读，可以考虑使用竖屏滚动观看。后面我再抽空看看有没有啥其他好的方法处理下，抱歉。

**Comment by lekai63** [comment]
嗯嗯 明白。感谢op
