### ISSUE TITLE
关于图1.1放置错误

### ISSUE THREAD

**Issue by infinitesum** [careywyr/UnderstandingDeepLearning-ZH-CN#3]
非常感谢您的辛勤工作。我最近在阅读时，发现在第 1 章中似乎有一处图片放置错误。图1.1，上面为翻译，下面为原文 PDF

![Screenshot-2024-07-23-at-18 00 49](https://github.com/user-attachments/assets/dddf637b-21e7-47db-9cf9-d0182306591c)

**Comment by careywyr** [comment]
这是因为我没有完全按照原PDF的方式进行排版，而且中英文的字数不一样，每一页容纳内容也不一样，所以绝大部分图片位置跟原来还是有一定差别的，但我尽量也让图片没有偏离引用的地方太多，这次没做超链，下个正式版本会加入超链方便图片和公式的跳转。
